import { Analytics } from "@vercel/analytics/react";
import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "./lib/registry";
import { ThemeProvider } from "./theme-provider";
import { cookies } from "next/headers";

const ibm_plex_mono = IBM_Plex_Mono({ weight: "500", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Douyu For Dummies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider initialTheme={cookies().get("theme")?.value}>
      <body className={ibm_plex_mono.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        <Analytics />
      </body>
    </ThemeProvider>
  );
}
